#!/bin/bash
#调用anbox脚本 卸载应用
(. /usr/bin/deepin-androidbox-appmgr-demo.sh uninstall -p #androidName#)

res=$?

if [ "$res" == 0 ] ;then
   echo "#debName# uninstall successfully"
 else
   echo "#debName# uninstall Failed: $res"
fi

#判断是否残留apk 删除残留
if [ -e  #apkDir#/#apkName# ] ;then
   rm -rf  #apkDir#/#apkName#
fi

if [ -e #desktopDir#/#appDesktop# ];then
   rm -rf #desktopDir#/#appDesktop#
fi

if [ -e #desktopDir#/#appIcon# ];then
    rm -rf #desktopDir#/#appIcon#
fi



exit "$res"



